version: "3.9"
services:
  auction-db:
    image: postgres # using postgres image from docker hub
    restart: always
    container_name: auction-db
    ports:
      - 5432:5432 # mapping container port 5432 to host port 5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
